/*
 * Generate docs/features.md from the in-client help.
 *
 * The help topics in `help.js` are the canonical documentation: they are what a
 * player actually reads, and they are covered by tests that fail when a feature
 * gains an editor without gaining a topic.
 *
 * Writing a second copy by hand for GitHub would guarantee the two drift, and
 * the stale one is always the one a newcomer finds first. So this generates the
 * markdown from the same data.
 *
 *     node scripts/export_help_docs.js
 *
 * `help.js` is an IIFE taking `window` and `document`. It touches `document`
 * only inside rendering functions we never call, so a bare object is enough of
 * a stand-in to reach the topic data.
 */

"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const HELP_JS = path.join(
    ROOT, "contrib", "aetos_webclient", "static", "aetos", "js", "help.js"
);
const OUTPUT = path.join(ROOT, "docs", "features.md");

global.window = {};
global.document = {};
require(HELP_JS);

const TOPICS = global.window.AetosHelp.TOPICS;

function slug(text) {
    return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

const lines = [];

lines.push("# Feature reference");
lines.push("");
lines.push(
    "Generated from the client's own help topics by `scripts/export_help_docs.js`. " +
    "Do not edit this file by hand -- edit `help.js` and regenerate, so the page " +
    "you are reading and the help a player sees can never disagree."
);
lines.push("");
lines.push(
    "In the client, press `F1` for the same content, searchable and filtered to " +
    "the features your game actually permits."
);
lines.push("");
lines.push("## Contents");
lines.push("");

let currentGroup = null;
TOPICS.forEach((topic) => {
    if (topic.group !== currentGroup) {
        currentGroup = topic.group;
        lines.push("");
        lines.push(`**${currentGroup}**`);
        lines.push("");
    }
    const gate = topic.requires
        ? ` *(only when the game permits \`${topic.requires}\`)*`
        : "";
    lines.push(`- [${topic.title}](#${slug(topic.title)}) — ${topic.summary}${gate}`);
});

lines.push("");
lines.push("---");
lines.push("");

TOPICS.forEach((topic) => {
    lines.push(`## ${topic.title}`);
    lines.push("");
    lines.push(`*${topic.summary}*`);
    lines.push("");
    if (topic.requires) {
        lines.push(
            `> This topic appears only on a game whose \`AETOS_AUTOMATION\` ` +
            `permits \`${topic.requires}\`.`
        );
        lines.push("");
    }

    (topic.sections || []).forEach((section) => {
        if (section.heading) {
            lines.push(`### ${section.heading}`);
            lines.push("");
        }
        (section.body || []).forEach((paragraph) => {
            lines.push(paragraph);
            lines.push("");
        });
        if (section.example) {
            // Fenced without a language: the blocks are a mix of Python,
            // Aetos Script and plain tables, and a wrong highlighter is worse
            // than none.
            lines.push("```");
            lines.push(section.example);
            lines.push("```");
            lines.push("");
        }
        if (section.keys) {
            lines.push("| Key | Does |");
            lines.push("| --- | --- |");
            section.keys.forEach((row) => {
                lines.push(`| \`${row[0]}\` | ${row[1]} |`);
            });
            lines.push("");
        }
    });

    lines.push("---");
    lines.push("");
});

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT, lines.join("\n").replace(/\n{3,}/g, "\n\n"), "utf8");

console.log(`Wrote ${OUTPUT} (${TOPICS.length} topics)`);
